/**
 * Copyright 2020 Quantiphi, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use strict";

/**
 * Maps dialogflow intent with its controller
 */

const intents = {
    "Default Welcome Intent": require("./intents/default-welcome-intent"),
    "AgentTransfer": require("./intents/agent-transfer"),
    "AgentTransferMaxAttempt": require("./intents/agent-transfer"),
    "Agent Transfer Failed": require("./intents/agent-transfer-fail"),
    "Default No Input": require("./intents/agent-transfer-fail"),
    "AgentRequestInitialQuery": require("./intents/agent-request-initial-query"),
    "OpenRequest": require("./intents/open-request/open-request"),
    "OpenRequestSomethingElse": require("./intents/set-df-responses"),
    "NewRoadsideRequest": require("./intents/set-df-responses"),
    "OpenRequestFallback": require("./intents/set-df-responses"),
    "NewRequest": require("./intents/new-request/new-request"),
    "NewRequestFallback": require("./intents/set-df-responses"),
    "NewRequestSomethingElse": require("./intents/set-df-responses"),
    "SubmitNewRequest": require("./intents/set-df-responses"),
    "WelcomeBlacklistedNumber": require("./intents/blacklist/welcome-blacklisted-number"),
    "NewCallbackNumberRequest": require("./intents/blacklist/new-callback-number-request"),
    "WelcomeBlacklistedNumberFallback": require("./intents/set-df-responses"),
    "ConfigureMessage": require("./intents/configure-message"),
    "NewCallbackNumberConfirmed": require("./intents/blacklist/new-callback-number/new-callback-number-confirmed"),
    "NewCallbackNumberIncorrect": require("./intents/blacklist/new-callback-number/new-callback-number-incorrect"),
    "ConfigureMessageFallback": require("./intents/set-df-responses"),
    "TriggerSMS": require("./intents/trigger-sms"),
    "SMSReceived": require("./intents/set-df-responses"),
    "SMSNotReceived": require("./intents/set-df-responses"),
    "TriggerSMSFallback": require("./intents/set-df-responses"),
    "Default Fallback Intent": require("./intents/default-fallback-intent"),
    "NewCallbackNumberFallback": require("./intents/set-df-responses"),
    "CarrierTypeInput": require("./intents/ask-carrier-type/carrier-type-input.js"),
    "SilentOptionGetDTMF": require("./intents/silent-option-dtmf"),
    "OpenRequestNoInput": require("./intents/set-df-responses"),
    "NewRequestNoInput": require("./intents/set-df-responses"),
    "WelcomeBlacklistedNoInput": require("./intents/set-df-responses"),
    "NewCallbackNoInput": require("./intents/set-df-responses"),
    "AskCarrierTypeFallback": require("./intents/set-df-responses"),
    "CarrierTypeNoInput": require("./intents/set-df-responses"),
    "AskCarrierType": require("./intents/set-df-responses"),
    "ConfigureMessageNoInput": require("./intents/set-df-responses"),
    "TriggerSMSNoInput": require("./intents/set-df-responses"),
    "ConfigOfferVisualPathYes": require("./intents/set-df-responses"),
    "ConfigOfferVisualPathNo": require("./intents/set-df-responses"),
    "OpenRequestAskNewRequest": require("./intents/set-df-responses"),
    "AgentTransferReason": require("./intents/set-df-responses"),
    "NewRequestNo": require("./intents/set-df-responses"),
    "OpenRequestETA": require("./intents/open-request/open-request-eta"),
    "OpenRequestAnythingElseYes": require("./intents/set-df-responses"),
    "OpenRequestAnythingElseNo": require("./intents/set-df-responses"),
    "OpenRequestAnythingElseFallback": require("./intents/set-df-responses"),
    "OpenRequestAnythingElseNoInput": require("./intents/set-df-responses"),
    "OpenRequestAnythingElseRepeat": require("./intents/set-df-responses"),
    "AgentTransferReasonNoInput": require("./intents/set-df-responses"),
    "AgentTransferReasonFallback": require("./intents/set-df-responses"),
    "OpenRequestReason": require("./intents/open-request/open-request-eta"),
    "NewRequestReason": require("./intents/set-df-responses"),
    "ConfigNewNumberRejectSMS": require("./intents/set-df-responses"),
    "ConfigForceVisualPath": require("./intents/set-df-responses"),
    "ConfigOfferVisualPathAgent": require("./intents/set-df-responses"),
    "ConfigOfferVisualUnconfirmed": require("./intents/set-df-responses"),
    "ConfigOfferVisualUnconfirmedFallback": require("./intents/set-df-responses"),
    "ConfigOfferVisualUnconfirmedNoInput": require("./intents/set-df-responses"),
    "ConfigOfferVisualUnconfirmedAgent": require("./intents/set-df-responses"),
    "ConfigOfferVisualUnconfirmedNo": require("./intents/set-df-responses"),
    "ConfigOfferVisualUnconfirmedYes": require("./intents/set-df-responses"),
    "ConfigForceVisualPathNo": require("./intents/set-df-responses"),
    "ConfigForceVisualPathYes": require("./intents/trigger-sms"),
    "ConfigForceVisualPathFallback": require("./intents/trigger-sms"),
    "ConfigForceVisualPathNoInput": require("./intents/trigger-sms"),
    "ConfigOfferVisualRequestOnCall": require("./intents/set-df-responses"),
    "ConfigOfferVisualUnconfirmedRequestOnCall": require("./intents/set-df-responses"),
    "TriggerSMSConnectAgent": require("./intents/trigger-sms-connect-agent"),
    "DontHaveMobile": require("./intents/set-df-responses"),
    "RequestOnCall": require("./intents/set-df-responses"),
    "RequestOnCallAccident": require("./intents/set-df-responses"),
    "RequestOnCallTalkToAgent": require("./intents/set-df-responses"),
    "RequestOnCallDontKnow": require("./intents/set-df-responses"),
    "RequestOnCallNoInput": require("./intents/set-df-responses"),
    "RequestOnCallFallback": require("./intents/set-df-responses"),
    "RequestOnCallVent": require("./intents/collect-new-request-information/request-on-call/request-on-call-vent"),
    "ServiceTypeYes": require("./intents/set-df-responses"),
    "ServiceTypeYesFallback": require("./intents/set-df-responses"),
    "ServiceTypeYesNoInput": require("./intents/set-df-responses"),
    "ServiceTypeYesImmediate": require("./intents/set-df-responses"),
    "ServiceTypeYesLater": require("./intents/set-df-responses"),
    "ServiceTypeNo": require("./intents/set-df-responses"),
    "ServiceTypeConfirmationFallback": require("./intents/set-df-responses"),
    "ServiceTypeConfirmationNoInput": require("./intents/set-df-responses"),
    "UserWithVehicleConfirmationFallback": require("./intents/set-df-responses"),
    "UserWithVehicleConfirmationNoInput": require("./intents/set-df-responses"),
    "UserWithVehicleYes": require("./intents/collect-new-request-information/user-with-vehicle"),
    "UserWithVehicleNo": require("./intents/collect-new-request-information/user-with-vehicle"),
    "BatteryServiceFlow": require("./intents/set-df-responses"),
    "BatteryServiceFlowFallback": require("./intents/set-df-responses"),
    "BatteryServiceFlowNoInput": require("./intents/set-df-responses"),
    "CaptureFuelType": require("./intents/collect-new-request-information/capture-fuel-type"),
    "JumpStartAttemptedYes": require("./intents/set-df-responses"),
    "JumpStartAttemptedNo": require("./intents/set-df-responses"),
    "JumpStartAttemptedFallback": require("./intents/set-df-responses"),
    "JumpStartAttemptedNoInput": require("./intents/set-df-responses"),
    "LocationCollection": require("./intents/collect-new-request-information/location-determination/location-collection"),
    "SysLocationCollection": require("./intents/collect-new-request-information/location-determination/location-collection"),
    "SysLocationCollectionNoInput": require("./intents/set-df-responses"),
    "SysLocationCollectionFallback": require("./intents/set-df-responses"),
    "SysLocationDontKnow": require("./intents/set-df-responses"),
    "GeoCityCollection": require("./intents/collect-new-request-information/location-determination/geo-city-collection"),
    "GeoCityCollectionFallback": require("./intents/set-df-responses"),
    "GeoCityCollectionNoInput": require("./intents/set-df-responses"),
    "GeoStateCollection": require("./intents/collect-new-request-information/location-determination/geo-state-collection"),
    "GeoStateCollectionFallback": require("./intents/set-df-responses"),
    "GeoStateCollectionNoInput": require("./intents/set-df-responses"),
    "LocationCaptureIncorrect": require("./intents/set-df-responses"),
    "LocationConfirmed": require("./intents/set-df-responses"),
    "LocationCollectionFallback": require("./intents/set-df-responses"),
    "LocationCollectionNoInput": require("./intents/set-df-responses"),
    "CollectLocationType": require("./intents/set-df-responses"),
    "LocationConfirmedNoInput": require("./intents/set-df-responses"),
    "LocationConfirmedFallback": require("./intents/set-df-responses"),
    "LocateMeFlow": require("./intents/set-df-responses"),
    "LocateMeFlowNoInput": require("./intents/set-df-responses"),
    "LocateMeFlowFallback": require("./intents/set-df-responses"),
    "NotWithVehicleForLocateMe": require("./intents/set-df-responses"),
    "WithVehicleForLocateMe": require("./intents/set-df-responses"),
    "LocateMeTextPermission": require("./intents/set-df-responses"),
    "LocateMeTextPermissionYes": require("./intents/set-df-responses"),
    "LocateMeTextPermissionNo": require("./intents/set-df-responses"),
    "LocateMeTextPermissionNoInput": require("./intents/set-df-responses"),
    "LocateMeTextPermissionFallback": require("./intents/set-df-responses"),
    "LocateMeTextNumberPermissionYes": require("./intents/set-df-responses"),
    "LocateMeTextNumberPermissionNo": require("./intents/set-df-responses"),
    "LocateMeTextNumberPermissionNoInput": require("./intents/set-df-responses"),
    "LocateMeTextNumberPermissionFallback": require("./intents/set-df-responses"),
    "DontKnowFuelType": require("./intents/set-df-responses"),
    "SendLocateMeSMS": require("./intents/collect-new-request-information/location-determination/send-locate-me-sms"),
    "SendLocateMeSMSFallback": require("./intents/collect-new-request-information/get-location-from-locate-me"),
    "SendLocateMeSMSNoInput": require("./intents/collect-new-request-information/get-location-from-locate-me"),
    "DetermineProblem": require("./intents/set-df-responses"),

    // policy intents
    "VinPolicyNumberConfirm": require("./intents/set-df-responses"),
    "VinPolicyNumberConfirmNoInput": require("./intents/set-df-responses"),
    "VinPolicyNumberConfirmFallback": require("./intents/set-df-responses"),
    "VinPolicyNumberConfirmNo": require("./intents/set-df-responses"),
    "ConfirmName": require("./intents/set-df-responses"),
    "ConfirmNameAgentTransfer": require("./intents/set-df-responses"),
    "ConfirmCarDetailsNoInput": require("./intents/set-df-responses"),
    "ConfirmNameNoInput": require("./intents/set-df-responses"),
    "ConfirmNameFallback": require("./intents/set-df-responses"),
    "ConfirmCarDetailsFallback": require("./intents/set-df-responses"),
    "CarMakeAndModel": require("./intents/policy/make-model"),
    "CarMakeAndModelNoInput": require("./intents/set-df-responses"),
    "CarMakeAndModelFallback": require("./intents/set-df-responses"),
    "CarMakeAndModelResponse": require("./intents/set-df-responses"),
    "VehicleStuckYes": require("./intents/collect-new-request-information/vehicle-stuck-detection"),
    "VehicleStuckNo": require("./intents/collect-new-request-information/vehicle-stuck-detection"),
    "LockedOutYes": require("./intents/collect-new-request-information/locked-out-detection"),
    "LockedOutNo": require("./intents/collect-new-request-information/locked-out-detection"),
    "BatteryServiceYes": require('./intents/collect-new-request-information/battery-service-detection'),
    "BatteryServiceNo": require('./intents/collect-new-request-information/battery-service-detection'),
    "FlatTireYes": require('./intents/collect-new-request-information/flat-tire-detection'),
    "FlatTireNo": require('./intents/collect-new-request-information/flat-tire-detection'),
    "CaptureTireToAttend": require("./intents/collect-new-request-information/flat-tire-flow/capture-tire"),
    "SpareTireYes": require("./intents/collect-new-request-information/flat-tire-flow/spare-tire"),
    "SpareTireNo": require("./intents/collect-new-request-information/flat-tire-flow/spare-tire"),
    "TiresImpacted": require("./intents/collect-new-request-information/flat-tire-flow/tires-impacted"),
    "CaptureVehicleFuel": require("./intents/collect-new-request-information/capture-fuel-type"),
    "VehicleStuckFlowYes": require("./intents/collect-new-request-information/vehicle-stuck-flow/vehicle-stuck-flow"),
    "VehicleStuckFlowNo": require("./intents/collect-new-request-information/vehicle-stuck-flow/vehicle-stuck-flow"),
    "VehicleDrivableYes": require("./intents/collect-new-request-information/vehicle-stuck-flow/vehicle-drivable"),
    "VehicleDrivableNo": require("./intents/collect-new-request-information/vehicle-stuck-flow/vehicle-drivable"),
    "LockedOutFlowYes": require("./intents/collect-new-request-information/locked-out-flow/locked-out"),
    "LockedOutFlowNo": require("./intents/collect-new-request-information/locked-out-flow/locked-out"),
    "FlatTireFlow": require("./intents/set-df-responses"),
    "OutOfFuel": require("./intents/set-df-responses"),
    "VehicleStuckFlow": require("./intents/set-df-responses"),
    "LockedOutFlow": require("./intents/set-df-responses"),
    "TowService": require("./intents/set-df-responses"),
    "CaptureLicensePlate": require("./intents/collect-new-request-information/tow-service-flow/capture-license-plate"),
    "CaptureLicensePlateYes": require("./intents/collect-new-request-information/tow-service-flow/capture-license-plate-correct"),
    "CaptureLicensePlateNo": require("./intents/collect-new-request-information/tow-service-flow/capture-license-plate-correct"),
    "FlatTireFlowNoInput": require("./intents/set-df-responses"),
    "OutOfFuelNoInput": require("./intents/set-df-responses"),
    "CaptureTireToAttendNoInput": require("./intents/set-df-responses"),
    "VehicleDrivableNoInput": require("./intents/set-df-responses"),
    "VehicleStuckFlowNoInput": require("./intents/set-df-responses"),
    "LockedOutFlowNoInput": require("./intents/set-df-responses"),
    "OutOfFuelFallback": require("./intents/set-df-responses"),
    "VehicleStuckFlowFallback": require("./intents/set-df-responses"),
    "VehicleDrivableFallback": require("./intents/set-df-responses"),
    "LockedOutFlowFallback": require("./intents/set-df-responses"),
    "FlatTireFlowFallback": require("./intents/set-df-responses"),
    "CaptureTireToAttendFallback": require("./intents/set-df-responses"),
    "SpareTireFallback": require("./intents/set-df-responses"),
    "TowServiceFallback": require("./intents/set-df-responses"),
    "CaptureLicensePlateFallback": require("./intents/set-df-responses"),
    "BatteryServiceFallback": require("./intents/set-df-responses"),
    "LockedOutFallback": require("./intents/set-df-responses"),
    "FlatTireFallback": require("./intents/set-df-responses"),
    "VehicleStuckFallback": require("./intents/set-df-responses"),
    "SpareTireNoInput": require("./intents/set-df-responses"),
    "TowServiceNoInput": require("./intents/set-df-responses"),
    "CaptureLicensePlateNoInput": require("./intents/set-df-responses"),
    "BatteryServiceNoInput": require("./intents/set-df-responses"),
    "LockedOutNoInput": require("./intents/set-df-responses"),
    "FlatTireNoInput": require("./intents/set-df-responses"),
    "VehicleStuckNoInput": require("./intents/set-df-responses"),
    "SpareTireDontKnow": require("./intents/collect-new-request-information/flat-tire-flow/spare-tire"),

    // mvp2 intents( chat bot intents )
    "Chat Default Welcome Intent": require("./intents/mvp2/chat-default-welcome-intent"),
    "ChatCancelRequest": require("./intents/mvp2/cancel-request.js"),
    "ChatCancelRequestConfirmYes": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatCancelRequestConfirmNo": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatCancelRequestConfirmNoFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatCancelRequestConfirmYesFallback": require("./intents/mvp2/cancel-request-confirm"),
    "ChatCancelRequestConfirmFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatCancelRequestConfirm": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatCancelReqSuccessFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatCancelReqSuccess": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSpeakToSP": require("./intents/mvp2/speak-to-sp"),
    "ChatGetCallbackNumber": require("./intents/mvp2/get-callback-number"),
    "ChatGetCallbackNumberFallback": require("./intents/mvp2/get-callback-number"),
    "ChatTowTruckTime": require("./intents/mvp2/tow-truck-time"),
    "ChatTowTruckInfo": require("./intents/mvp2/tow-truck-info"),
    "ChatTowTruckInfoFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatNewRequest": require("./intents/mvp2/new-request"),
    "ChatSmsNotReceived": require("./intents/mvp2/did-not-get-sms"),
    "ChatSmsNotReceivedFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSomeThingElse": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatUserNotCancelRequest": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatInvoice": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSPNotArrived": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSPNotArrivedFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatETAPassed": require("./intents/mvp2/eta-passed"),
    "ChatETAPassedFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatETAPassedYes": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatChangeRequestFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatChangePickUpLocation": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatEditRequestFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatChangeDropOffLocation": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatTalkToAgent": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatTalkToAgentUserQuery": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSMSTriggered": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSMSTriggeredFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSMSWait": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSMSWaitFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSpeakToSPFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSPNotResponding": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSPNotRespondingFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatThanks": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatSPNotRespondingYes": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatGetPickUpLocation": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatGetDropOffLocation": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatAgentTransfer": require("./intents/mvp2/agent-transfer"),
    "ChatEditRequest": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatTowTruckTimeFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatGetQuery": require("./intents/mvp2/get-query"),
    "ChatUserQuery": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatDefaultWelcomeIntentFallback": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatUnplannedAgentTransfer": require("./intents/mvp2/set-df-responses-mvp2"),
    "ChatCustomerDisconnected": require("./intents/mvp2/session-end")
};

module.exports = intents;
